services:
  php:
    restart: unless-stopped
    build:
      context: ..
      target: production
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      SSL_MODE: "off"
      PHP_OPCACHE_ENABLE: 1
      AUTORUN_ENABLED: "false"
      PHP_DATE_TIMEZONE: "UTC"
